package renderer

import (
	"fmt"
	"io"
	"path/filepath"
	"strings"
	"time"

	"github.com/volodymyrkovtun/confradar/internal/health"
	"github.com/volodymyrkovtun/confradar/internal/scanner"
)

// MarkdownRenderer outputs scan results as a Markdown report.
type MarkdownRenderer struct {
	Issues     []health.HealthIssue
	IncludeTOC bool
}

// Render writes a Markdown report to the writer.
func (m *MarkdownRenderer) Render(result *scanner.ScanResult, w io.Writer) error {
	projectName := filepath.Base(result.Root)

	// Header.
	fmt.Fprintf(w, "# %s — Configuration Report\n\n", projectName)
	fmt.Fprintf(w, "> Generated by confradar on %s\n\n", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Fprintf(w, "**%d** config files across **%d** categories (scanned in %s)\n\n",
		result.TotalFiles, len(result.Ordered), result.Duration.Round(1e6))

	// TOC.
	if m.IncludeTOC {
		fmt.Fprintln(w, "## Table of Contents")
		fmt.Fprintln(w)
		for _, cat := range result.Ordered {
			anchor := strings.ToLower(strings.ReplaceAll(cat.Name, " ", "-"))
			anchor = strings.ReplaceAll(anchor, "/", "")
			fmt.Fprintf(w, "- [%s %s](#%s) (%d files)\n", cat.Icon, cat.Name, anchor, len(cat.Files))
		}
		if len(m.Issues) > 0 {
			fmt.Fprintln(w, "- [Health Issues](#health-issues)")
		}
		fmt.Fprintln(w)
	}

	// Categories.
	for _, cat := range result.Ordered {
		fmt.Fprintf(w, "## %s %s\n\n", cat.Icon, cat.Name)

		fmt.Fprintln(w, "| File | Pattern | Size |")
		fmt.Fprintln(w, "|------|---------|------|")
		for _, f := range cat.Files {
			fmt.Fprintf(w, "| `%s` | %s | %s |\n",
				f.RelPath, f.PatternName, FormatSize(f.Size))
		}
		fmt.Fprintln(w)
	}

	// Health Issues.
	if len(m.Issues) > 0 {
		fmt.Fprintln(w, "## Health Issues")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "| Severity | Type | Message | File |")
		fmt.Fprintln(w, "|----------|------|---------|------|")
		for _, issue := range m.Issues {
			icon := "ℹ️"
			switch issue.Severity {
			case health.SeverityError:
				icon = "❌"
			case health.SeverityWarning:
				icon = "⚠️"
			}
			fmt.Fprintf(w, "| %s %s | %s | %s | `%s` |\n",
				icon, issue.Severity, issue.CheckType, issue.Message, issue.File)
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "---")
	fmt.Fprintln(w, "*Report generated by [confradar](https://github.com/volodymyrkovtun/confradar)*")

	return nil
}
